[package]
name = "blipcoard-desktop"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.85"

[workspace]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
blip-api = { path = "../../../crates/blip-api" }
blip-config = { path = "../../../crates/blip-config" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tauri = { version = "2.11.5", features = [] }
tauri-plugin-shell = "2.3.3"
thiserror = "2.0.17"

[lints.rust]
unsafe_code = "warn"

[lints.clippy]
all = "warn"
